## Learn Numpy
Learn Numpy from basics

In [5]:
import numpy as np

### Creating Array from List 

In [6]:
arr_1d = np.array([1,2,3,4,5])
print("1d array",arr_1d)

arr_2d = np.array([[1,2,6],[3,4,5]])
print("2d array",arr_2d)

1d array [1 2 3 4 5]
2d array [[1 2 6]
 [3 4 5]]


### List vs Numpy array

In [9]:
py_list = [1,2,3]
print("list multiplication : ",py_list*2)

numpy_arr = np.array([6,7,8])
print("numpy array multiplication : ",numpy_arr*2)


list multiplication :  [1, 2, 3, 1, 2, 3]
numpy array multiplication :  [12 14 16]


### Creating Array from scratch

In [25]:
zeros = np.zeros((3,4))
print("Zero array: \n",zeros)

ones = np.ones((3,3))
print("ones array: \n",ones)

constant_arr = np.full((3,2),5)
print("Const array: \n",constant_arr)

random = np.random.random((2,4))
print("Random array")
print(random)

sequence = np.arange(0,10,2)
print("Sequence:\n",sequence)



Zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Const array: 
 [[5 5]
 [5 5]
 [5 5]]
Random array
[[0.37861815 0.55727302 0.73128934 0.90404108]
 [0.17802252 0.93747586 0.46985971 0.5587121 ]]
Sequence:
 [0 2 4 6 8]
