### Numpy operations

In [2]:
import numpy as np;

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing: ",arr[2:6])
print(arr[4:])
print(arr[:4])
print("Negative Indexing :",arr[-3:-1])
print(arr[1:5:3])
print(arr[::2])


Basic slicing:  [3 4 5 6]
[ 5  6  7  8  9 10]
[1 2 3 4]
Negative Indexing : [8 9]
[2 5]
[1 3 5 7 9]


## Array Indexing 

In [4]:
arr = np.array([4,5,6,8,9])
print(arr[0])
print(arr[1])
print(arr[1]+arr[3])

4
5
13


### Access 2d arr

In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


it is allowed in numpy not in regular python 

In [13]:
arr_2d = np.array([[1,2,3],
                   [5,6,7],
                   [8,9,6]]
                  )

print("Entire row -- ",arr_2d[1])
print("Entire column -- ",arr_2d[:,1])

Entire row --  [5 6 7]
Entire column --  [2 6 9]


## Sorting

In [15]:
unsorted = np.array([8,6,5,9,7,3,6,1,8])
print("Sorted array -> ",np.sort(unsorted))

Sorted array ->  [1 3 5 6 6 7 8 8 9]


In [5]:
arr_2d_unsort = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d array by col",np.sort(arr_2d_unsort,axis=0))
print("Sorted 2d array by row left to right",np.sort(arr_2d_unsort,axis=1))

Sorted 2d array by col [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array by row left to right [[1 3]
 [1 2]
 [2 3]]


## Filter

In [20]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_num = numbers[numbers%2==0]
print("Even numbers: ",even_num)

Even numbers:  [2 4 6 8]
